import type { DependencyGraphBase } from './dependency-graph/base';
import type { DependencyGraphSchema } from './schema';
import { Subject } from './subject';
import type { OnCollectionChangeArgs, OnCollectionDeleteArgs, OnGlobalChangeArgs } from './types';

/**
 * This class is an implementation for the service that is a singleton instance.
 * Through this class you interact with the plugin.
 */
export class DependencyGraphServiceImpl extends Subject {
	/**
	 * Schema of dependencies generated by SchemaBuilder
	 */
	schema!: DependencyGraphSchema;

	/**
	 * The concrete instance of the dependency graph
	 */
	dependencyGraph?: DependencyGraphBase;

	/**
	 * Function called exclusively by the `afterChange` hook in each collection.
	 *
	 * @param args
	 */
	async onCollectionChange(args: OnCollectionChangeArgs): Promise<void> {
		if (!this.dependencyGraph) {
			return;
		}

		const { doc, previousDoc, collection, operation } = args;

		await this.dependencyGraph.purgeDependentOn({
			collection,
			id: previousDoc.id,
		});

		await this.dependencyGraph.extractDependenciesFromDoc(
			{
				collection,
				id: doc.id,
			},
			doc,
			this.schema.collections[collection] || [],
		);

		if (operation === 'create') {
			await this.notifySubscribers({
				type: 'create',
				doc,
				collection,
			});
		} else if (operation === 'update') {
			await this.notifySubscribers({
				type: 'update',
				doc,
				previousDoc,
				collection,
			});
		}
	}

	/**
	 * Function called exclusively by the `afterDelete` hook in each collection.
	 *
	 * @param args
	 */
	async onCollectionDelete(args: OnCollectionDeleteArgs): Promise<void> {
		if (!this.dependencyGraph) {
			return;
		}

		const { id, doc, collection } = args;

		await this.notifySubscribers({
			type: 'delete',
			doc,
			collection,
		});

		await this.dependencyGraph.deleteResource({
			collection,
			id: id.toString(),
		});
	}

	/**
	 * Function called exclusively by the `afterChange` hook in each global.
	 *
	 * @param args
	 */
	async onGlobalChange(args: OnGlobalChangeArgs): Promise<void> {
		if (!this.dependencyGraph) {
			return;
		}

		const { doc, previousDoc } = args;
		const resource = {
			global: doc.globalType,
		};

		await this.dependencyGraph.purgeDependentOn(resource);

		await this.dependencyGraph.extractDependenciesFromDoc(
			resource,
			doc,
			this.schema.globals[doc.globalType] || [],
		);

		await this.notifySubscribers({
			type: 'update',
			doc,
			previousDoc,
			global: doc.globalType,
		});
	}
}
